### ISSUE TITLE
When libreoffice is open, this gem produces error "No such file or directory @ rb_sysopen"

### ISSUE THREAD

**Issue by TheRealGuardDogGPS** [ricn/libreconv#10]
I have noticed everytime I have libreoffice open, and then this gem attempts to convert the word to pdf, it gives me an error "No such file or directory @ rb_sysopen". However, as soon as I close out of libreoffice, the errors go away. How come?

**Comment by ricn** [comment]
It's a known problem that happens with more recent versions of OpenOffice. I've solved it in another library that I have developed using Elixir: https://github.com/ricn/librex/blob/master/lib/librex.ex#L129. I don't have the time to maintain this gem anymore so pull requests that fixes this problem is welcome.
